CREATE DATABASE IF NOT EXISTS app_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'app'@'localhost' IDENTIFIED BY 'app';
CREATE USER IF NOT EXISTS 'app'@'127.0.0.1' IDENTIFIED BY 'app';
CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'app';

GRANT ALL PRIVILEGES ON app_db.* TO 'app'@'localhost';
GRANT ALL PRIVILEGES ON app_db.* TO 'app'@'127.0.0.1';
GRANT ALL PRIVILEGES ON app_db.* TO 'app'@'%';

FLUSH PRIVILEGES;
